#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/maxabsinlst.cpp /autograder/source/maxabsinlst.cpp

cd /autograder/source

g++ main.cpp maxabsinlst.cpp

python3 run_tests.py > /autograder/results/results.json
