#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/avgoflst.cpp /autograder/source/avgoflst.cpp

cd /autograder/source

g++ main.cpp avgoflst.cpp

python3 run_tests.py > /autograder/results/results.json
