#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/remainingwords.cpp /autograder/source/remainingwords.cpp

cd /autograder/source

g++ main.cpp remainingwords.cpp

python3 run_tests.py > /autograder/results/results.json
