#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/firstword.cpp /autograder/source/firstword.cpp

cd /autograder/source

g++ main.cpp firstword.cpp

python3 run_tests.py > /autograder/results/results.json
