#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/stringsplitter.cpp /autograder/source/stringsplitter.cpp

cd /autograder/source
g++ stringsplitter.cpp

python3 run_tests.py > /autograder/results/results.json
