#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/gradeclass.cpp /autograder/source/gradeclass.cpp

cd /autograder/source
g++ gradeclass.cpp

python3 run_tests.py > /autograder/results/results.json
