#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/bmimetric2.cpp /autograder/source/bmimetric2.cpp

cd /autograder/source
g++ bmimetric2.cpp

python3 run_tests.py > /autograder/results/results.json
