#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/counter.cpp /autograder/source/counter.cpp

cd /autograder/source
g++ counter.cpp

python3 run_tests.py > /autograder/results/results.json
