#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/isleapyearc.cpp /autograder/source/isleapyearc.cpp

cd /autograder/source

g++ isleapyearc.cpp

python3 run_tests.py > /autograder/results/results.json
