#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/cashregister.cpp /autograder/source/cashregister.cpp

cd /autograder/source
g++ cashregister.cpp

python3 run_tests.py > /autograder/results/results.json
