#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/csvexport.cpp /autograder/source/csvexport.cpp

cd /autograder/source

g++ main.cpp csvimport.cpp csvexport.cpp

python3 run_tests.py > /autograder/results/results.json
