#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/stack.h /autograder/source/stack.h

cd /autograder/source

g++ main.cpp 

python3 run_tests.py > /autograder/results/results.json
