#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/getdoubles.cpp /autograder/source/getdoubles.cpp

cd /autograder/source

g++ main.cpp getdoubles.cpp

python3 run_tests.py > /autograder/results/results.json
