#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/countoddeven.cpp /autograder/source/countoddeven.cpp

cd /autograder/source
g++ countoddeven.cpp

python3 run_tests.py > /autograder/results/results.json
