#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/evennumbers.cpp /autograder/source/evennumbers.cpp

cd /autograder/source
g++ evennumbers.cpp

python3 run_tests.py > /autograder/results/results.json
