#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/bmiimperial.cpp /autograder/source/bmiimperial.cpp

cd /autograder/source
g++ bmiimperial.cpp

python3 run_tests.py > /autograder/results/results.json
