#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/mergesort.cpp /autograder/source/mergesort.cpp

cd /autograder/source

g++ main.cpp mergesort.cpp

python3 run_tests.py > /autograder/results/results.json
