#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/hello.cpp /autograder/source/hello.cpp

cd /autograder/source
g++ hello.cpp

python3 run_tests.py > /autograder/results/results.json
