#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/ispalindrome.cpp /autograder/source/ispalindrome.cpp

cd /autograder/source

g++ main.cpp ispalindrome.cpp

python3 run_tests.py > /autograder/results/results.json
