#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/addnodeh.cpp /autograder/source/addnodeh.cpp

cd /autograder/source

g++ main.cpp addnodeh.cpp

python3 run_tests.py > /autograder/results/results.json
