#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/chartype.cpp /autograder/source/chartype.cpp

cd /autograder/source
g++ chartype.cpp

python3 run_tests.py > /autograder/results/results.json
