#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/lsearch.cpp /autograder/source/lsearch.cpp

cd /autograder/source

g++ main.cpp lsearch.cpp

python3 run_tests.py > /autograder/results/results.json
