#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/avl.cpp /autograder/source/avl.cpp

cd /autograder/source

g++ main.cpp avl.cpp

python3 run_tests.py > /autograder/results/results.json
