#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/bst.h /autograder/source/bst.h

cd /autograder/source

g++ main.cpp 

python3 run_tests.py > /autograder/results/results.json
