#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/isleapyearf.cpp /autograder/source/isleapyearf.cpp

cd /autograder/source

g++ main.cpp isleapyearf.cpp

python3 run_tests.py > /autograder/results/results.json
