#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/bsearch.cpp /autograder/source/bsearch.cpp

cd /autograder/source

g++ main.cpp bsearch.cpp

python3 run_tests.py > /autograder/results/results.json
