#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/csvimport.cpp /autograder/source/csvimport.cpp

cd /autograder/source

g++ main.cpp csvimport.cpp 

python3 run_tests.py > /autograder/results/results.json
